"""empty message

Revision ID: 0beccc55ad5e
Revises: 
Create Date: 2025-03-02 11:42:29.131847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0beccc55ad5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('treatment_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.drop_column('content')
        batch_op.drop_column('address')
        batch_op.drop_column('appointment_time')
        batch_op.drop_column('name')
        batch_op.drop_column('phone')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('first_visit_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('dental_condition', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('teeth_position')
        batch_op.drop_column('appointment_date')
        batch_op.drop_column('notes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('appointment_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('teeth_position', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('dental_condition')
        batch_op.drop_column('first_visit_date')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('appointment_time', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('cost')
        batch_op.drop_column('treatment_type')
        batch_op.drop_column('status')
        batch_op.drop_column('appointment_date')
        batch_op.drop_column('patient_id')

    op.create_table('patient',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('teeth_position', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
