import '../models/material.dart' as material_models;

/// 牙医常用材料初始化数据
class DentalMaterialsInit {
  /// 获取牙医常用材料列表
  static List<material_models.MaterialInfo> getDefaultMaterials() {
    return [
      // 药品类
      _createMaterial('M001', '阿莫西林胶囊', '盒', '药品'),
      _createMaterial('M002', '甲硝唑片', '盒', '药品'),
      _createMaterial('M003', '布洛芬片', '盒', '药品'),
      _createMaterial('M004', '头孢克肟胶囊', '盒', '药品'),
      _createMaterial('M005', '罗红霉素片', '盒', '药品'),
      _createMaterial('M006', '替硝唑片', '盒', '药品'),
      _createMaterial('M007', '克林霉素胶囊', '盒', '药品'),
      _createMaterial('M008', '奥硝唑片', '盒', '药品'),
      _createMaterial('M009', '阿奇霉素片', '盒', '药品'),
      _createMaterial('M010', '左氧氟沙星片', '盒', '药品'),
      
      // 局部麻醉药
      _createMaterial('M011', '利多卡因注射液', '支', '局部麻醉药'),
      _createMaterial('M012', '阿替卡因注射液', '支', '局部麻醉药'),
      _createMaterial('M013', '布比卡因注射液', '支', '局部麻醉药'),
      _createMaterial('M014', '普鲁卡因注射液', '支', '局部麻醉药'),
      _createMaterial('M015', '甲哌卡因注射液', '支', '局部麻醉药'),
      
      // 消毒用品
      _createMaterial('M016', '碘伏消毒液', '瓶', '消毒用品'),
      _createMaterial('M017', '酒精消毒液', '瓶', '消毒用品'),
      _createMaterial('M018', '双氧水', '瓶', '消毒用品'),
      _createMaterial('M019', '生理盐水', '瓶', '消毒用品'),
      _createMaterial('M020', '洗必泰漱口液', '瓶', '消毒用品'),
      _createMaterial('M021', '过氧化氢溶液', '瓶', '消毒用品'),
      _createMaterial('M022', '戊二醛消毒液', '瓶', '消毒用品'),
      _createMaterial('M023', '次氯酸钠溶液', '瓶', '消毒用品'),
      
      // 一次性用品
      _createMaterial('M024', '一次性手套', '盒', '一次性用品'),
      _createMaterial('M025', '一次性口罩', '盒', '一次性用品'),
      _createMaterial('M026', '一次性帽子', '盒', '一次性用品'),
      _createMaterial('M027', '一次性注射器', '支', '一次性用品'),
      _createMaterial('M028', '一次性针头', '盒', '一次性用品'),
      _createMaterial('M029', '一次性吸唾管', '包', '一次性用品'),
      _createMaterial('M030', '一次性围巾', '包', '一次性用品'),
      _createMaterial('M031', '一次性治疗巾', '包', '一次性用品'),
      _createMaterial('M032', '一次性托盘', '个', '一次性用品'),
      _createMaterial('M033', '一次性漱口杯', '包', '一次性用品'),
      _createMaterial('M034', '一次性棉签', '包', '一次性用品'),
      _createMaterial('M035', '一次性纱布', '包', '一次性用品'),
      _createMaterial('M036', '一次性棉球', '包', '一次性用品'),
      _createMaterial('M037', '一次性牙线', '盒', '一次性用品'),
      _createMaterial('M038', '一次性牙签', '盒', '一次性用品'),
      
      // 牙科材料
      _createMaterial('M039', '玻璃离子水门汀', '盒', '牙科材料'),
      _createMaterial('M040', '复合树脂', '盒', '牙科材料'),
      _createMaterial('M041', '光固化树脂', '盒', '牙科材料'),
      _createMaterial('M042', '银汞合金', '盒', '牙科材料'),
      _createMaterial('M043', '氧化锌水门汀', '盒', '牙科材料'),
      _createMaterial('M044', '磷酸锌水门汀', '盒', '牙科材料'),
      _createMaterial('M045', '聚羧酸锌水门汀', '盒', '牙科材料'),
      _createMaterial('M046', '氢氧化钙', '盒', '牙科材料'),
      _createMaterial('M047', '三氧化矿物凝聚体', '盒', '牙科材料'),
      _createMaterial('M048', '根管充填糊剂', '支', '牙科材料'),
      _createMaterial('M049', '根管封闭剂', '支', '牙科材料'),
      _createMaterial('M050', '牙本质粘接剂', '瓶', '牙科材料'),
      _createMaterial('M051', '釉质粘接剂', '瓶', '牙科材料'),
      _createMaterial('M052', '窝沟封闭剂', '支', '牙科材料'),
      _createMaterial('M053', '脱敏剂', '瓶', '牙科材料'),
      _createMaterial('M054', '漂白剂', '盒', '牙科材料'),
      _createMaterial('M055', '氟化物凝胶', '支', '牙科材料'),
      _createMaterial('M056', '氟化物漱口液', '瓶', '牙科材料'),
      
      // 牙科器械
      _createMaterial('M057', '探针', '把', '牙科器械'),
      _createMaterial('M058', '镊子', '把', '牙科器械'),
      _createMaterial('M059', '刮匙', '把', '牙科器械'),
      _createMaterial('M060', '挖匙', '把', '牙科器械'),
      _createMaterial('M061', '充填器', '把', '牙科器械'),
      _createMaterial('M062', '雕刻刀', '把', '牙科器械'),
      _createMaterial('M063', '抛光器', '把', '牙科器械'),
      
      // 根管治疗器械 - K型根管锉
      _createMaterial('M064', 'K型根管锉 08#', '支', '根管治疗器械'),
      _createMaterial('M065', 'K型根管锉 10#', '支', '根管治疗器械'),
      _createMaterial('M066', 'K型根管锉 15#', '支', '根管治疗器械'),
      _createMaterial('M067', 'K型根管锉 20#', '支', '根管治疗器械'),
      _createMaterial('M068', 'K型根管锉 25#', '支', '根管治疗器械'),
      _createMaterial('M069', 'K型根管锉 30#', '支', '根管治疗器械'),
      _createMaterial('M070', 'K型根管锉 35#', '支', '根管治疗器械'),
      _createMaterial('M071', 'K型根管锉 40#', '支', '根管治疗器械'),
      _createMaterial('M072', 'K型根管锉 45#', '支', '根管治疗器械'),
      _createMaterial('M073', 'K型根管锉 50#', '支', '根管治疗器械'),
      _createMaterial('M074', 'K型根管锉 55#', '支', '根管治疗器械'),
      _createMaterial('M075', 'K型根管锉 60#', '支', '根管治疗器械'),
      _createMaterial('M076', 'K型根管锉 70#', '支', '根管治疗器械'),
      _createMaterial('M077', 'K型根管锉 80#', '支', '根管治疗器械'),
      _createMaterial('M078', 'K型根管锉 90#', '支', '根管治疗器械'),
      _createMaterial('M079', 'K型根管锉 100#', '支', '根管治疗器械'),
      _createMaterial('M080', 'K型根管锉 110#', '支', '根管治疗器械'),
      _createMaterial('M081', 'K型根管锉 120#', '支', '根管治疗器械'),
      _createMaterial('M082', 'K型根管锉 130#', '支', '根管治疗器械'),
      _createMaterial('M083', 'K型根管锉 140#', '支', '根管治疗器械'),
      _createMaterial('M084', 'K型根管锉 150#', '支', '根管治疗器械'),
      
      // 根管扩大针
      _createMaterial('M085', '根管扩大针 08#', '支', '根管治疗器械'),
      _createMaterial('M086', '根管扩大针 10#', '支', '根管治疗器械'),
      _createMaterial('M087', '根管扩大针 15#', '支', '根管治疗器械'),
      _createMaterial('M088', '根管扩大针 20#', '支', '根管治疗器械'),
      _createMaterial('M089', '根管扩大针 25#', '支', '根管治疗器械'),
      _createMaterial('M090', '根管扩大针 30#', '支', '根管治疗器械'),
      _createMaterial('M091', '根管扩大针 35#', '支', '根管治疗器械'),
      _createMaterial('M092', '根管扩大针 40#', '支', '根管治疗器械'),
      _createMaterial('M093', '根管扩大针 45#', '支', '根管治疗器械'),
      _createMaterial('M094', '根管扩大针 50#', '支', '根管治疗器械'),
      _createMaterial('M095', '根管扩大针 55#', '支', '根管治疗器械'),
      _createMaterial('M096', '根管扩大针 60#', '支', '根管治疗器械'),
      _createMaterial('M097', '根管扩大针 70#', '支', '根管治疗器械'),
      _createMaterial('M098', '根管扩大针 80#', '支', '根管治疗器械'),
      _createMaterial('M099', '根管扩大针 90#', '支', '根管治疗器械'),
      _createMaterial('M100', '根管扩大针 100#', '支', '根管治疗器械'),
      _createMaterial('M101', '根管扩大针 110#', '支', '根管治疗器械'),
      _createMaterial('M102', '根管扩大针 120#', '支', '根管治疗器械'),
      _createMaterial('M103', '根管扩大针 130#', '支', '根管治疗器械'),
      _createMaterial('M104', '根管扩大针 140#', '支', '根管治疗器械'),
      _createMaterial('M105', '根管扩大针 150#', '支', '根管治疗器械'),
      
      // 拔髓针
      _createMaterial('M106', '拔髓针 08#', '支', '根管治疗器械'),
      _createMaterial('M107', '拔髓针 10#', '支', '根管治疗器械'),
      _createMaterial('M108', '拔髓针 15#', '支', '根管治疗器械'),
      _createMaterial('M109', '拔髓针 20#', '支', '根管治疗器械'),
      _createMaterial('M110', '拔髓针 25#', '支', '根管治疗器械'),
      _createMaterial('M111', '拔髓针 30#', '支', '根管治疗器械'),
      _createMaterial('M112', '拔髓针 35#', '支', '根管治疗器械'),
      _createMaterial('M113', '拔髓针 40#', '支', '根管治疗器械'),
      _createMaterial('M114', '拔髓针 45#', '支', '根管治疗器械'),
      _createMaterial('M115', '拔髓针 50#', '支', '根管治疗器械'),
      _createMaterial('M116', '拔髓针 55#', '支', '根管治疗器械'),
      _createMaterial('M117', '拔髓针 60#', '支', '根管治疗器械'),
      _createMaterial('M118', '拔髓针 70#', '支', '根管治疗器械'),
      _createMaterial('M119', '拔髓针 80#', '支', '根管治疗器械'),
      _createMaterial('M120', '拔髓针 90#', '支', '根管治疗器械'),
      _createMaterial('M121', '拔髓针 100#', '支', '根管治疗器械'),
      _createMaterial('M122', '拔髓针 110#', '支', '根管治疗器械'),
      _createMaterial('M123', '拔髓针 120#', '支', '根管治疗器械'),
      _createMaterial('M124', '拔髓针 130#', '支', '根管治疗器械'),
      _createMaterial('M125', '拔髓针 140#', '支', '根管治疗器械'),
      _createMaterial('M126', '拔髓针 150#', '支', '根管治疗器械'),
      
      // 其他根管器械
      _createMaterial('M127', '根管测量器', '支', '根管治疗器械'),
      _createMaterial('M128', '根管充填器', '支', '根管治疗器械'),
      _createMaterial('M129', '牙周探针', '把', '牙科器械'),
      _createMaterial('M130', '牙周刮治器', '把', '牙科器械'),
      _createMaterial('M131', '超声波洁牙机头', '个', '牙科器械'),
      _createMaterial('M132', '气动洁牙机头', '个', '牙科器械'),
      _createMaterial('M133', '高速手机', '台', '牙科器械'),
      _createMaterial('M134', '低速手机', '台', '牙科器械'),
      _createMaterial('M135', '光固化灯', '台', '牙科器械'),
      _createMaterial('M136', 'X光机', '台', '牙科器械'),
      _createMaterial('M137', '口腔内窥镜', '台', '牙科器械'),
      _createMaterial('M138', '牙科椅', '台', '牙科器械'),
      _createMaterial('M139', '吸唾器', '台', '牙科器械'),
      _createMaterial('M140', '三用枪', '把', '牙科器械'),
      _createMaterial('M141', '水枪', '把', '牙科器械'),
      _createMaterial('M142', '气枪', '把', '牙科器械'),
      
      // 牙科耗材 - 车针系列
      _createMaterial('M143', '高速车针 1#', '支', '牙科耗材'),
      _createMaterial('M144', '高速车针 2#', '支', '牙科耗材'),
      _createMaterial('M145', '高速车针 4#', '支', '牙科耗材'),
      _createMaterial('M146', '高速车针 6#', '支', '牙科耗材'),
      _createMaterial('M147', '高速车针 8#', '支', '牙科耗材'),
      _createMaterial('M148', '高速车针 10#', '支', '牙科耗材'),
      _createMaterial('M149', '高速车针 12#', '支', '牙科耗材'),
      _createMaterial('M150', '高速车针 14#', '支', '牙科耗材'),
      _createMaterial('M151', '高速车针 16#', '支', '牙科耗材'),
      _createMaterial('M152', '高速车针 18#', '支', '牙科耗材'),
      _createMaterial('M153', '高速车针 20#', '支', '牙科耗材'),
      _createMaterial('M154', '高速车针 22#', '支', '牙科耗材'),
      _createMaterial('M155', '高速车针 24#', '支', '牙科耗材'),
      _createMaterial('M156', '高速车针 26#', '支', '牙科耗材'),
      _createMaterial('M157', '高速车针 28#', '支', '牙科耗材'),
      _createMaterial('M158', '高速车针 30#', '支', '牙科耗材'),
      _createMaterial('M159', '高速车针 32#', '支', '牙科耗材'),
      _createMaterial('M160', '高速车针 34#', '支', '牙科耗材'),
      _createMaterial('M161', '高速车针 36#', '支', '牙科耗材'),
      _createMaterial('M162', '高速车针 38#', '支', '牙科耗材'),
      _createMaterial('M163', '高速车针 40#', '支', '牙科耗材'),
      
      // 金刚砂车针
      _createMaterial('M164', '金刚砂车针 1#', '支', '牙科耗材'),
      _createMaterial('M165', '金刚砂车针 2#', '支', '牙科耗材'),
      _createMaterial('M166', '金刚砂车针 4#', '支', '牙科耗材'),
      _createMaterial('M167', '金刚砂车针 6#', '支', '牙科耗材'),
      _createMaterial('M168', '金刚砂车针 8#', '支', '牙科耗材'),
      _createMaterial('M169', '金刚砂车针 10#', '支', '牙科耗材'),
      _createMaterial('M170', '金刚砂车针 12#', '支', '牙科耗材'),
      _createMaterial('M171', '金刚砂车针 14#', '支', '牙科耗材'),
      _createMaterial('M172', '金刚砂车针 16#', '支', '牙科耗材'),
      _createMaterial('M173', '金刚砂车针 18#', '支', '牙科耗材'),
      _createMaterial('M174', '金刚砂车针 20#', '支', '牙科耗材'),
      _createMaterial('M175', '金刚砂车针 22#', '支', '牙科耗材'),
      _createMaterial('M176', '金刚砂车针 24#', '支', '牙科耗材'),
      _createMaterial('M177', '金刚砂车针 26#', '支', '牙科耗材'),
      _createMaterial('M178', '金刚砂车针 28#', '支', '牙科耗材'),
      _createMaterial('M179', '金刚砂车针 30#', '支', '牙科耗材'),
      _createMaterial('M180', '金刚砂车针 32#', '支', '牙科耗材'),
      _createMaterial('M181', '金刚砂车针 34#', '支', '牙科耗材'),
      _createMaterial('M182', '金刚砂车针 36#', '支', '牙科耗材'),
      _createMaterial('M183', '金刚砂车针 38#', '支', '牙科耗材'),
      _createMaterial('M184', '金刚砂车针 40#', '支', '牙科耗材'),
      
      // 钨钢车针
      _createMaterial('M185', '钨钢车针 1#', '支', '牙科耗材'),
      _createMaterial('M186', '钨钢车针 2#', '支', '牙科耗材'),
      _createMaterial('M187', '钨钢车针 4#', '支', '牙科耗材'),
      _createMaterial('M188', '钨钢车针 6#', '支', '牙科耗材'),
      _createMaterial('M189', '钨钢车针 8#', '支', '牙科耗材'),
      _createMaterial('M190', '钨钢车针 10#', '支', '牙科耗材'),
      _createMaterial('M191', '钨钢车针 12#', '支', '牙科耗材'),
      _createMaterial('M192', '钨钢车针 14#', '支', '牙科耗材'),
      _createMaterial('M193', '钨钢车针 16#', '支', '牙科耗材'),
      _createMaterial('M194', '钨钢车针 18#', '支', '牙科耗材'),
      _createMaterial('M195', '钨钢车针 20#', '支', '牙科耗材'),
      _createMaterial('M196', '钨钢车针 22#', '支', '牙科耗材'),
      _createMaterial('M197', '钨钢车针 24#', '支', '牙科耗材'),
      _createMaterial('M198', '钨钢车针 26#', '支', '牙科耗材'),
      _createMaterial('M199', '钨钢车针 28#', '支', '牙科耗材'),
      _createMaterial('M200', '钨钢车针 30#', '支', '牙科耗材'),
      _createMaterial('M201', '钨钢车针 32#', '支', '牙科耗材'),
      _createMaterial('M202', '钨钢车针 34#', '支', '牙科耗材'),
      _createMaterial('M203', '钨钢车针 36#', '支', '牙科耗材'),
      _createMaterial('M204', '钨钢车针 38#', '支', '牙科耗材'),
      _createMaterial('M205', '钨钢车针 40#', '支', '牙科耗材'),
      
      // 其他耗材
      _createMaterial('M206', '抛光杯', '盒', '牙科耗材'),
      _createMaterial('M207', '抛光刷', '盒', '牙科耗材'),
      _createMaterial('M208', '砂纸', '张', '牙科耗材'),
      _createMaterial('M209', '砂条', '根', '牙科耗材'),
      _createMaterial('M210', '橡皮障', '包', '牙科耗材'),
      _createMaterial('M211', '橡皮障夹', '盒', '牙科耗材'),
      _createMaterial('M212', '橡皮障打孔器', '个', '牙科耗材'),
      _createMaterial('M213', '橡皮障支架', '个', '牙科耗材'),
      _createMaterial('M214', '楔子', '盒', '牙科耗材'),
      _createMaterial('M215', '成形片', '盒', '牙科耗材'),
      _createMaterial('M216', '成形片夹', '把', '牙科耗材'),
      _createMaterial('M217', '分离圈', '盒', '牙科耗材'),
      _createMaterial('M218', '分离环', '盒', '牙科耗材'),
      
      // 牙胶尖系列
      _createMaterial('M219', '牙胶尖 15#', '支', '牙科耗材'),
      _createMaterial('M220', '牙胶尖 20#', '支', '牙科耗材'),
      _createMaterial('M221', '牙胶尖 25#', '支', '牙科耗材'),
      _createMaterial('M222', '牙胶尖 30#', '支', '牙科耗材'),
      _createMaterial('M223', '牙胶尖 35#', '支', '牙科耗材'),
      _createMaterial('M224', '牙胶尖 40#', '支', '牙科耗材'),
      _createMaterial('M225', '牙胶尖 45#', '支', '牙科耗材'),
      _createMaterial('M226', '牙胶尖 50#', '支', '牙科耗材'),
      _createMaterial('M227', '牙胶尖 55#', '支', '牙科耗材'),
      _createMaterial('M228', '牙胶尖 60#', '支', '牙科耗材'),
      _createMaterial('M229', '牙胶尖 70#', '支', '牙科耗材'),
      _createMaterial('M230', '牙胶尖 80#', '支', '牙科耗材'),
      _createMaterial('M231', '牙胶尖 90#', '支', '牙科耗材'),
      _createMaterial('M232', '牙胶尖 100#', '支', '牙科耗材'),
      _createMaterial('M233', '牙胶尖 110#', '支', '牙科耗材'),
      _createMaterial('M234', '牙胶尖 120#', '支', '牙科耗材'),
      _createMaterial('M235', '牙胶尖 130#', '支', '牙科耗材'),
      _createMaterial('M236', '牙胶尖 140#', '支', '牙科耗材'),
      _createMaterial('M237', '牙胶尖 150#', '支', '牙科耗材'),
      
      // 牙胶条和牙胶块
      _createMaterial('M238', '牙胶条', '盒', '牙科耗材'),
      _createMaterial('M239', '牙胶块', '盒', '牙科耗材'),
      
      // 正畸材料 - 弓丝系列
      _createMaterial('M240', '镍钛弓丝 0.012"', '根', '正畸材料'),
      _createMaterial('M241', '镍钛弓丝 0.014"', '根', '正畸材料'),
      _createMaterial('M242', '镍钛弓丝 0.016"', '根', '正畸材料'),
      _createMaterial('M243', '镍钛弓丝 0.018"', '根', '正畸材料'),
      _createMaterial('M244', '镍钛弓丝 0.020"', '根', '正畸材料'),
      _createMaterial('M245', '镍钛弓丝 0.022"', '根', '正畸材料'),
      _createMaterial('M246', '镍钛弓丝 0.025"', '根', '正畸材料'),
      _createMaterial('M247', '镍钛弓丝 0.028"', '根', '正畸材料'),
      _createMaterial('M248', '镍钛弓丝 0.030"', '根', '正畸材料'),
      _createMaterial('M249', '镍钛弓丝 0.032"', '根', '正畸材料'),
      _createMaterial('M250', '镍钛弓丝 0.035"', '根', '正畸材料'),
      _createMaterial('M251', '镍钛弓丝 0.038"', '根', '正畸材料'),
      _createMaterial('M252', '镍钛弓丝 0.040"', '根', '正畸材料'),
      _createMaterial('M253', '镍钛弓丝 0.045"', '根', '正畸材料'),
      _createMaterial('M254', '镍钛弓丝 0.050"', '根', '正畸材料'),
      
      // 不锈钢弓丝
      _createMaterial('M255', '不锈钢弓丝 0.012"', '根', '正畸材料'),
      _createMaterial('M256', '不锈钢弓丝 0.014"', '根', '正畸材料'),
      _createMaterial('M257', '不锈钢弓丝 0.016"', '根', '正畸材料'),
      _createMaterial('M258', '不锈钢弓丝 0.018"', '根', '正畸材料'),
      _createMaterial('M259', '不锈钢弓丝 0.020"', '根', '正畸材料'),
      _createMaterial('M260', '不锈钢弓丝 0.022"', '根', '正畸材料'),
      _createMaterial('M261', '不锈钢弓丝 0.025"', '根', '正畸材料'),
      _createMaterial('M262', '不锈钢弓丝 0.028"', '根', '正畸材料'),
      _createMaterial('M263', '不锈钢弓丝 0.030"', '根', '正畸材料'),
      _createMaterial('M264', '不锈钢弓丝 0.032"', '根', '正畸材料'),
      _createMaterial('M265', '不锈钢弓丝 0.035"', '根', '正畸材料'),
      _createMaterial('M266', '不锈钢弓丝 0.038"', '根', '正畸材料'),
      _createMaterial('M267', '不锈钢弓丝 0.040"', '根', '正畸材料'),
      _createMaterial('M268', '不锈钢弓丝 0.045"', '根', '正畸材料'),
      _createMaterial('M269', '不锈钢弓丝 0.050"', '根', '正畸材料'),
      
      // 结扎丝系列
      _createMaterial('M270', '结扎丝 0.008"', '卷', '正畸材料'),
      _createMaterial('M271', '结扎丝 0.009"', '卷', '正畸材料'),
      _createMaterial('M272', '结扎丝 0.010"', '卷', '正畸材料'),
      _createMaterial('M273', '结扎丝 0.012"', '卷', '正畸材料'),
      _createMaterial('M274', '结扎丝 0.014"', '卷', '正畸材料'),
      _createMaterial('M275', '结扎丝 0.016"', '卷', '正畸材料'),
      _createMaterial('M276', '结扎丝 0.018"', '卷', '正畸材料'),
      _createMaterial('M277', '结扎丝 0.020"', '卷', '正畸材料'),
      _createMaterial('M278', '结扎丝 0.022"', '卷', '正畸材料'),
      _createMaterial('M279', '结扎丝 0.025"', '卷', '正畸材料'),
      
      // 口腔护理用品
      _createMaterial('M280', '牙膏', '支', '口腔护理用品'),
      _createMaterial('M281', '牙刷', '把', '口腔护理用品'),
      _createMaterial('M282', '漱口水', '瓶', '口腔护理用品'),
      _createMaterial('M283', '牙线', '盒', '口腔护理用品'),
      _createMaterial('M284', '牙签', '盒', '口腔护理用品'),
      _createMaterial('M285', '舌苔刷', '把', '口腔护理用品'),
      _createMaterial('M286', '口腔喷雾', '瓶', '口腔护理用品'),
      _createMaterial('M287', '口腔凝胶', '支', '口腔护理用品'),
      _createMaterial('M288', '口腔贴片', '盒', '口腔护理用品'),
      _createMaterial('M289', '口腔含片', '盒', '口腔护理用品'),
      
      // 防护用品
      _createMaterial('M290', '防护眼镜', '副', '防护用品'),
      _createMaterial('M291', '防护面罩', '个', '防护用品'),
      _createMaterial('M292', '防护服', '件', '防护用品'),
      _createMaterial('M293', '防护鞋套', '双', '防护用品'),
      _createMaterial('M294', '防护袖套', '对', '防护用品'),
      
      // 其他用品
      _createMaterial('M295', '标签纸', '卷', '办公用品'),
      _createMaterial('M296', '记录本', '本', '办公用品'),
      _createMaterial('M297', '笔', '支', '办公用品'),
      _createMaterial('M298', '剪刀', '把', '办公用品'),
      _createMaterial('M299', '尺子', '把', '办公用品'),
      _createMaterial('M300', '放大镜', '个', '办公用品'),
      _createMaterial('M301', '计时器', '个', '办公用品'),
      _createMaterial('M302', '温度计', '支', '办公用品'),
      _createMaterial('M303', '血压计', '台', '办公用品'),
      _createMaterial('M304', '听诊器', '个', '办公用品'),
    ];
  }
  
  /// 创建材料对象
  static material_models.MaterialInfo _createMaterial(String code, String name, String unit, String type) {
    return material_models.MaterialInfo(
      id: null,
      materialName: name,
      materialCode: code,
      materialType: type, // 新增：材料类型
      unit: unit,
      defaultPrice: 0.0,
      supplier: null,
      description: null,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
  }
}
